### ISSUE TITLE
Cursor - Gboard autocomplete causes double cursor

### ISSUE THREAD

**Issue by LogicNg** [visual-space/visual-editor#114]
First of all, thank you for all the effort you've put in, I can't stress enough how much more readable the codes are! While playing around with the example, for Android devices that use Gboard (probably the most popular keyboard for Android), if you autocomplete the last word of the line and hit enter, the cursor on the last line won't hide correctly, and it causes double cursor. For other keyboard such as Microsoft SwiftKey, this problem does not exist.

FYI, this problem also exists in flutter_quill, so it isn't due to refactoring.

https://user-images.githubusercontent.com/53685306/187080896-80b9f660-36b0-434a-856e-0a9fc513ba80.mp4

**Comment by LogicNg** [comment]
I found out  the cause, GBoard insert a space after every word it autocompletes. If the last word of the line is auto complete, when user press the enter button, it replace spalce (32) to line feed (10) automatically. For Microsoft Swift Board, it just inserts line feed after space.

**Comment by adrian-moisa** [comment]
> First of all, thank you for all the effort you've put in, I can't stress enough how much more readable the codes are! 
Thank you for the feedback. I'm really happy to hear my efforts are helping. I'm still digging deeply in the library to add more features and the more I dig the more I document. So in time it will be even better.

> FYI, this problem also exists in flutter_quill, so it isn't due to refactoring.
Good to know this particular detail.

So, is this problem still affecting you? Did you manage to find a fix? At the moment I don't have a clear explanation of what could it be. Also I'm having a hard time to slice out time. There's a huge backlog of far bigger issues that I'm consuming. Can't promise a fast resolution. I'll label this issue as open for contributions. For sure sooner or later it will have to be fixed. If not by the community, I'll find myself time or someone from my team once we go closer to our go live deadline. I'm interested to fix all such issues. In the end my goal is to have a flawless editor. It will take some time but we will get there.
