### ISSUE TITLE
I need to embed the editor to a nestedscrollview,but it has initialize a scrollcontroller already, so it don't work

### ISSUE THREAD

**Issue by SmallCharm** [visual-space/visual-editor#115]
because I have some other fields in a page, I try to wrap them in a nestedscrollview,if set the scrollable to false,the editor bring cursor to view was not work,

**Comment by adrian-moisa** [comment]
It's possible to disable scroll behavior on the editor. Have you tried setting it on false?

<img width="509" alt="image" src="https://user-images.githubusercontent.com/11160141/192115392-83816861-8fde-4ca0-9195-b2917310e98b.png">

**Comment by adrian-moisa** [comment]
Closed, since no feedback was provided.
