### ISSUE TITLE
Inputs - Keyboard Shortcuts

### ISSUE THREAD

**Issue by garv-shah** [visual-space/visual-editor#163]
Flutter Quill recently had some commits that added support for keyboard shortcuts such as `ctrl + b` allowing a user to bold text. The quality of the [PR](https://github.com/singerdmx/flutter-quill/pull/986) doesn't seem to be the *best* but similar functionality could possibly also be considered for Visual Editor.

Another PR that adds typing shortcuts was also pushed [here](https://github.com/singerdmx/flutter-quill/pull/994)

Thanks!

**Comment by adrian-moisa** [comment]
Hey @garv-shah! Thanks for sharing this info. To be honest, I've been tracking Quill to see where it goes and I've already took notes of the interesting developments that we want to port over here, including this particular feature. Actually this feature will be essential for the next step: slash commands, mentions, hashtags. 

There was a learning period involved so I couldn't focus at all on keeping features parity. But by now I'm familiar with 90% of the code base and also have a few people helping around that are catching up. So we will keep improving the editor. I'm going trough the entire tickets list to weed out the duplicates, improve the specs and also add these additional ideas in the tickets list.

**Comment by darius859** [comment]
Added hotkeys for most of the styling buttons inside the toolbar, also added handling for inserting ordered and unordered lists by   typing either "1. " or "-" + spacebar. Did it in a much cleaner way. Created a service for typing shortcuts (TypingShortcutsService) which handles spacebar and tab key when pressed alone or with some text combination like above.  Also created a shortcuts utils for applying styling attributes (e.g. CTRL + B applies bold to selection).
