### ISSUE TITLE
Demos - Demo page for adding new elements in the document

### ISSUE THREAD

**Issue by sebastian0107** [visual-space/visual-editor#195]
We need a demo page to demonstrate how to add elements to the document (ex. how to make a button that insert a new H1 line)

**Comment by adrian-moisa** [comment]
We have added a demo showcasing how to programatically add elements in the page.

https://user-images.githubusercontent.com/11160141/208688948-675808af-deb1-4b97-a514-59be021911d3.mov

**Comment by sebastian0107** [comment]
We choose to add this page to show all clients how we can insert new elements at the end of the delta document by using only existing methods from the controller. Because there is no insert method available, this operation can be achieved by using a replacement (replaceText() )for the last element of the document.
