### ISSUE TITLE
Upgrade to i18n_extension: ^6.0.0

### ISSUE THREAD

**Issue by vd3d** [visual-space/visual-editor#196]
Hi,

I tried to add the Visual Editor, but it looks that some libraries are quite old, is it possible to upgrade i18n_extension to ^6.0.0?

Without this I got some incompatibilities with other libraries.

**Comment by adrian-moisa** [comment]
HI @vd3d. Late reply, holidays season. I'm usually not eager to update to x.0.0 versions because of potentially hidden bugs. I'll have a look by end of week to see what is the current state of affairs and if there.

**Comment by vd3d** [comment]
Hi @adrian-moisa , you're right. The version 6 is maybe too young.

But I've tested the version 5.0.1 and it looks stable.

**Comment by deliqs** [comment]
@adrian-moisa Any update on this? I'm not being able to update other packages due to this.
