### ISSUE TITLE
How can we make keep checklist style when double enter?

### ISSUE THREAD

**Issue by sonysm** [visual-space/visual-editor#201]
How can we make keep checklist style when double enter?

Like google keep checklist Todo list

**Comment by adrian-moisa** [comment]
There is a set of heuristics rules in the editor. They act as middleware between the code that registers the new input and the code rendering the document. 
 
<img width="629" alt="image" src="https://user-images.githubusercontent.com/11160141/213917904-6f269e82-0fdc-416c-9aac-f71dbeb0cde9.png">

There are 3 types of rules: insert, delete and retain. In the insert category there is the `AutoExitBlockRule`

<img width="392" alt="image" src="https://user-images.githubusercontent.com/11160141/213917972-edecef0a-0fa1-47e6-9891-8c18c4276886.png">

Right now there is no option to override internal rules. But we could easily extend the config object with a dictionary used to disable rules. If you are interested to implement this feature I can explain on [discord](https://discord.gg/XpGygmXde4) how it can be done. Right now I'm focused on other goals so I can't quickly implement it myself. I'd appreciate some extra hands on deck.

<img width="584" alt="image" src="https://user-images.githubusercontent.com/11160141/213918155-9c35b7d9-e63f-41c1-8296-1f203becbef1.png">

**Comment by adrian-moisa** [comment]
No follow up so far, closing
