### ISSUE TITLE
Sys - Upgrade to latest Flutter

### ISSUE THREAD

**Issue by jinyuanqing** [visual-space/visual-editor#202]
**AppData/Local/Pub/Cache/git/visual-editor-6497c03070365acf6707400bb41615ddb6f669d4/lib/main.dart:134:7: Error: The non-abstract class 'VisualEditorState' is missing implementations for these members:
 - TextInputClient.didChangeInputControl
 - TextInputClient.performSelector
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.**

It upgraded flutter yesterday and then reported an error
flutter :3.7.0

**Comment by adrian-moisa** [comment]
Thank you for reporting the issue! I'm currently at the end of a large refactoring process. I've made numerous changes to improve readability of the code. You can see the changes here #174 . I'll be done with this large set and at the end of the refactor I'll upgrade to Latest Flutter as well. Should be done in a couple of days. Sorry, can't push faster than this. After this large refactor is complete we will start making preparations to release it on pub dev.

**Comment by jinyuanqing** [comment]
It is recommended that different versions be released. The current way of using git addresses directly makes any changes to the source code unusable for projects that use the editor. This would not be the case if different releases were used

**Comment by adrian-moisa** [comment]
Agreed. For sure we will have multiple releases once we go live on pub dev. For now this is impractical since we are still in the stage of intensive refactoring. So at the moment the editor in in so called "live beta".

**Comment by adrian-moisa** [comment]
Fixed in #234. Apologies for the very long delay. I've been in crunch mode and I pushed my Flutter upgrade for half an year.
