### ISSUE TITLE
Sys - Improve docs

### ISSUE THREAD

**Issue by adrian-moisa** [visual-space/visual-editor#204]
- Update & improve readme example. It skips over the document part. Loading the document should be first (Retrieving a Document). Include the stateful parent widget in the example.
- Update migration document with latest architecture changes.
- Summary of most important changes in the top of this changelog. Explain: We prefer an architecture that is easy to maintain.
- Document the rules
- Improve Docs. Architecture overview: 
- JSON - delta - `documentM` - attributes - styles - compose - rules - refresh - build - docs and lines - editable line - test spans - renderbox - selection/markers/rectangles - inputs - callbacks
- Documents - Document the models graph and linked list
- Improve & Review all docs 
- Add explanation of modules

**Comment by dx314** [comment]
Currently the docs are out of date, as EditorController.basic no longer exists. As someone new to the project I actually have no idea how to get started.

**Comment by adrian-moisa** [comment]
Yes, we need to patch that and a bunch of other places. It's leftover work from the previous large refactor

**Comment by adrian-moisa** [comment]
Finally we have a grand document to overview the entire editor architecture: [Architecture Overview](https://github.com/visual-space/visual-editor/blob/develop/lib/shared/architecture-overview.md). Wished Quill had this document. It would have spared us half an year of work to fork and refactor Quill.
