### ISSUE TITLE
Selection - Restore copy paste styled text

### ISSUE THREAD

**Issue by darius859** [visual-space/visual-editor#218]
Looks like it is working on mobile, but not on web.

  void copySelection(SelectionChangedCause cause) {
    state.paste.copiedImageUrl = null;
    state.paste.plainText = _editorService.getSelectionPlainText();
    state.paste.styles = _stylesService.getAllIndividualSelectionStyles();

**Comment by adrian-moisa** [comment]
Duplicate of #8
