### ISSUE TITLE
Error: Type 'BidirectionalIterator' not found.

### ISSUE THREAD

**Issue by garv-shah** [visual-space/visual-editor#224]
Whenever I try to launch my Flutter app with Visual Editor on the latest version, I get the following error, and my app does not compile.

```
Error (Xcode): ../../../.pub-cache/git/visual-editor-6ccbb581a5abb6e48c9cf84fed2793df419cea6d/lib/editor/controllers/vertical-caret-movement-run.controller.dart:10:13: Error: Type 'BidirectionalIterator' not found.
```

How would I be able to fix this to try and get my app running again? Thanks!

**Comment by adrian-moisa** [comment]
Thank you for reporting! Duplicate of #229. If you happen to have time to double check what changed in Quill in migrate VE I'll merge your PR. Otherwise it will have to wait for 2 moths until we are over our go live stage at Visual Space.
