### ISSUE TITLE
Sys - Upgrade `gallery_saver`

### ISSUE THREAD

**Issue by LuchoTurtle** [visual-space/visual-editor#238]
Unfortunately, when installing `visual-editor`, it might run into versioning issues because it's dependent on [`gallery_saver`](https://pub.dev/packages/gallery_saver), which in turn depends on an outdated version of `http` 0.13.0. This creates issues where we can't upgrade `google_fonts` because of this. Additionally, if I try to install this package, I get the following error:

```
Because gallery_saver 2.3.2 depends on http ^0.13.3 and no versions of gallery_saver match >2.3.2 <3.0.0, gallery_saver ^2.3.2 requires http ^0.13.3.
So, because my_app depends on both gallery_saver ^2.3.2 and http ^1.0.0, version solving failed.
exit code 1
```

Because [`gallery_saver` is not maintained anymore](https://github.com/CarnegieTechnologies/gallery_saver/issues/206), it makes sense to replace it with [`gal`](https://pub.dev/packages/gal), which **is maintained** and serves the same purpose. 

After (hopefully) merging #237 , this will be the only last "outdated" dependency, which will make it possible to install `visual-studio` without a hinch (fingers crossed! 🤞).

I'll open a PR on this.

**Comment by adrian-moisa** [comment]
I'll have a look at these libs tomorrow evening. I've had some major overflow at the day job. Won't keep you hanging too much. I'd do it today but my brain is zapped. Maybe you'll have some time for a quick audio meeting.
