### ISSUE TITLE
Publish to pub.dev, and tagging?

### ISSUE THREAD

**Issue by dexterp** [visual-space/visual-editor#248]
Greetings,

Are there any plans to publish to pub.dev and create tagging?

This project has put in a lot of work, but I feel uncomfortable installing a package on a development branch as it can change at any time.

**Comment by dexterp** [comment]
Closing, I just saw in the README.md that the project is close to releasing.

**Comment by adrian-moisa** [comment]
We've had some delays on our main project, but we are soon to go live with the startup codebase. Therefore we will need to move attention here. Releasing on pub dev is planned ahead. Still committed to this plan. Wish we could move things faster.
