### ISSUE TITLE
Sys - Bump to Flutter 3.0

### ISSUE THREAD

**Issue by visual-space** [visual-space/visual-editor#25]
We need to upgrade the codebase to support Flutter 3.0. I'm currently researching what needs changing. Also got several fixes to make before tackling this one. Unless there is huge demand for 3.0 I'm not in an imediate hurry.

**Comment by adrian-moisa** [comment]
Yep, I was tracking the issue on their side. I'll attempt a fix these days. I'm also curios to see what will be their approach
