### ISSUE TITLE
Editor - RawEditorState does not implement TextInputClient

### ISSUE THREAD

**Issue by xclud** [visual-space/visual-editor#26]
`TextInputClient` has two methods which are not implemented by `RawEditorState` .
```
void insertTextPlaceholder(Size size);
```

```
void removeTextPlaceholder();
```

I guess they are new in Flutter 3.0.

#25

**Comment by adrian-moisa** [comment]
I'll read about the hooks and come up with an implementation. If they are new then it means Flutter 2 version can safely continue operating with the changes for 3.0.

**Comment by adrian-moisa** [comment]
This was fixed during refactoring. The current version runs under Flutter 3.0
