### ISSUE TITLE
Controller - No option to set autocorrect as false

### ISSUE THREAD

**Issue by adrian-moisa** [visual-space/visual-editor#27]
Found it in the Quill Repo

> [apurvbacancy](https://github.com/apurvbacancy) commented [3 days ago](https://github.com/singerdmx/flutter-quill/issues/819#issue-1239789234)
> I found that in quill editor by default text correction is true. I need to disable it. How can I do that?

At the moment I'm researching how this can be achieved. As far as I know [Flutter Quill](https://github.com/singerdmx/flutter-quill/issues/819) does not provide any override. Quill uses `TextLine` uses `RichText` to render the paragraphs. It might be possible to follow advice from [this StackOverflow question](https://stackoverflow.com/questions/55157290/how-to-disable-predictive-text-in-textfield-of-flutter). If neither `enableSuggestions` nor `autocorrect` can solve the problem, try setting keyboardType to `TextInputType.visiblePassword`. I'll inspect this issue once I've complete the refactoring work. At the moment this is rather low prio compared to other burning issues. At some point either me or one of my colleagues will take over this ticket. Until then, if you have a patch I can do the code review for you. Though I'd rather not accept any new contributions until we have the testing framework in place so we can start proper testing of new bug fixes to ensure they wont degrade in time.

Join us on [discord](https://discord.gg/XpGygmXde4) to get implementation advice and help or follow us on [YouTube Visual Coding](https://www.youtube.com/channel/UC2-5lfNbbErIds0Iuai8yfA) to learn more about the architecture of Visual Editor and other Flutter software architecture advice.

**Comment by adrian-moisa** [comment]
This issue seems to be related as well (Exception thrown when text get autocorrected). I'm adding here to document and possibly fix in the near future. https://github.com/singerdmx/flutter-quill/issues/820

**Comment by adrian-moisa** [comment]
Parked for now.

**Comment by manudicri** [comment]
Hi @adrian-moisa , is it possible to reopen this? I need the to disable autocorrect!
