### ISSUE TITLE
Plugins - Plugins registry, Composable Widgets

### ISSUE THREAD

**Issue by adrian-moisa** [visual-space/visual-editor#36]
- There are 2 categories of client devs: experts and beginners. They have conflicting needs. The experts want exposed hooks and slots such that they can insert their own custom implementations. Juniors on the other hand want to be able to extend the core by using plug and play components that require little understanding of the anatomy of the editor. So far we have created hooks and slots for experts. However to ensure the success of this editor we need to cater to both groups. Therefore we need to create a list of plugins that can be used in a plug and play fashion.
- After spending more time with the existing architecture and adding extra hooks and features I'm now realising that we already have quite a few ways of expanding the editor.
- Our next goal is to package the following features from the demo pages:
  - QuickMenu
  - Markers Attachments
  - Search
  - Link dialog
  - Image dialog
  - ToolbarMenu
- There are 2 potential architectures that can be used:
  - **Composable Widgets** - Some tasks require placement of editor extensions in a custom client app layout. We can use the same Controller pattern that is used to connect the Toolbar and Editor. We will export several more widgets that can be controlled via the editor controller. 
  - **Registry of plugins** - Each plugin is a class that can hook in the existing callbacks. We will need a manifest class.
- Provide demo pages, docs and tests

**--- OLDER NOTES ---**
**These notes were written before fully understanding the architecture of Quill. Now we are far better equipped to deal with this task**

This one will be super tricky. The goal is to provide middleware hooks to enable developers to insert their own custom code into the rendering logic of Visual Editor. For example, we could hook into the following life cycle stages. Some functionality already exist but it's done as simple callbacks. We need the ability to register plugins from external libs such that other vendors can operate in the current codebase without touching it. This would open the door for an entire ecosystem of extensions for Rich Text editiding. The possibilities are numerous

**Potential Hooks**
- Parsing the json into Delta doc
- Rendering the doc
- Applying the rules
- Changing the selection
- Initialising the embeds
- Scroll events
- Selections events
... many other events (let me know what you need)

**Potential APIs**
- Registry of plugins
- Exposed delta utils for getting text coordinates
- Feature Flags 

**What features could be plugged in?**
- Highlight and expand Jira Ticket via ID
- Highlight and expand github issue via ID / URL
- Generate adaptive image sizes (or use an existing service)
- Integration with Grammarly
- Support for multiple fonts from various vendors (Google Fonts for example)
- Text lens (zooms in)
- Macros
- Connector to existing icon fonts
- importer of clip art from royalty free artwork providers
- Connector to draw.io
- Connector to giphy
- Support for MD
- Convertors to docx, epub, etc
... the list goes on

Eager to hear your thoughts of what you need to be able to extend an instance of Quill with your own features. This work will take quite some time and dedication. The more devs contributing their knowhow the sooner we can deliver such a feature / ecosystem. 

Join us on [discord](https://discord.gg/XpGygmXde4) to get implementation advice and help or follow us on [YouTube Visual Coding](https://www.youtube.com/channel/UC2-5lfNbbErIds0Iuai8yfA) to learn more about the architecture of Visual Editor and other Flutter software architecture advice.

**Comment by kairan77** [comment]
the editor is missing one of the most important built in function for editor atm, ctrl+F keywords match highlight for find keyword match and rolling to the next match on find next.

the entire third block of list, I consider not worthwhile, build functional hooks rather than features. bear in mind many of the methioned services are not usable worldwide due to country firewalls... 

just work out key milestones during the rendering stage and expose hooks so that users can intervene and implement these features themselves easily. after all, this is only a rendering mechanism, as long as you give me a piece of data, give me the style you want, i get it rendered kind of scaffold library, why not just make it that way,  everyone's life would be much better.

**Comment by kairan77** [comment]
styles are lost during copy/cut paste, esp when copying from html/word, this would be a big game changer for my own apps.

**Comment by adrian-moisa** [comment]
@kairan77 **just work out key milestones during the rendering stage and expose hooks so that users can intervene and implement these features themselves easily.** - Yes indeed, hooks and middleware. that's what I'm thinking of. And I'll need help to identify various developer needs (places to hook into) and possibly feedback on the API design. At the moment it's not a high prio thing but in the future I can see some time allocated on this one.

**styles are lost during copy/cut paste, esp when copying from html/word, this would be a big game changer for my own apps.** - Yes indeed, same for me. Sooner than later this one will be in the pipeline. Though it's not an easy task at all... I suggest we continue this topic in [this ticket](https://github.com/visual-space/visual-editor/issues/8).

**Comment by adrian-moisa** [comment]
Closed, overengineering.
