### ISSUE TITLE
Blocks - Case insensitive links

### ISSUE THREAD

**Issue by adrian-moisa** [visual-space/visual-editor#48]
The regex needs to be improved to be case insensitive.
Original issue: https://github.com/singerdmx/flutter-quill/discussions/846

**Comment by kairan77** [comment]
i think auto lowercase the text as the user enters data is the way to go, regex is fine, since it benefit other use of the data by bringing in more certainty.

**Comment by adrian-moisa** [comment]
Might be data that is automatically inserted from other sources. And devs might want that we don't change their urls. My 2 cents.

**Comment by adrian-moisa** [comment]
Not sure if lower case will work on all URLs. Some urls could be case sensitive (should not, but can be)

**Comment by adrian-moisa** [comment]
Duplicated by #215
