### ISSUE TITLE
Blocks - Enumeration order messes up after indentation

### ISSUE THREAD

**Issue by adrian-moisa** [visual-space/visual-editor#56]
I noticed a small bug when implementing the Quill Editor. It happens when using the enumeration feature. I was pretty amazed when I found out that the indent button changes the enumeration from numbers to letters on indent, but it seems that once you go back to the first indentation level, the enumeration always resumes at '2'. Additionally, the one after that is a 2 as well. After that it will resort to normal.

![156074595-bafce533-5d55-41b9-acb3-21023bc97241](https://user-images.githubusercontent.com/11160141/175378694-fcae6f04-2661-4555-b1ff-ec7727ab94db.png)

I tried it as well for a list of say 9 items and then creating an indent at 9.a. Pressing Enter and the Decrease Indentation button make the item after 9 resort to 2. Writing some text and pressing Enter again yields a 2 again.

Original issue: https://github.com/singerdmx/flutter-quill/issues/696

Join us on [discord](https://discord.gg/XpGygmXde4) to get implementation advice and help or follow us on [YouTube Visual Coding](https://www.youtube.com/channel/UC2-5lfNbbErIds0Iuai8yfA) to learn more about the architecture of Visual Editor and other Flutter software architecture advice.

**Comment by kairan77** [comment]
I also found this problem when I also used quill to deliver my eula agreement. Stateful parser is much harder to implement than stateless parser when the state is not encoded within the document itself such as xml. 

Specifying the allowed levels of nesting is more important than fixing the problem on its face value. Global state of the parser is not easy to maintain correctly on long document with infinite nestings, esp in the future when users expect cut and paste with those styles should work like a charm (which i think is more important).

**Comment by adrian-moisa** [comment]
**Specifying the allowed levels of nesting is more important than fixing the problem on its face value.** - Not entirely sure what you mean. Can you expand?

**Comment by kairan77** [comment]
If you look at the parser code of quill, you see it's currently a stateless parser, it does not have a field varaible to record some parsing state, for example the treatment of "block", it actually uses local check (which i consider a hack) to see if the block is saturated locally to decide whether it is still in the block or it is dealing with the next element after the block.

This strategy works in most cases but won't work in general robustly. For example, apart from wrong continuation of list in list,  you also won't be able to have a list of Code or a list of Quote, or list in a Quote,

Take list in a quote for example, I do encounter these in some kitchen recipe books i have to process

Normal Paragraph

BeginQuote * blah blah blah, and the steps are
  1. do something
  2. do something else.
  3. etc
EndQuote

Normal Paragraph

This is what I consider two levels of nesting, You have the block quote as the first level, and the nested list as the second level.

It is also not difficult to imagine user may have 3 levels of nesting in some rare cases,

ListLevel1
  ListLevel2
    ListLevel3
  ListLevel2
ListLeve1

, but would be quite insane to have 4 levels of nesting

To fully support these features, you probably need a stateful parser with certain look ahead strategy, to figure out the context accurately in a rule based manner with the help of State. Remember such nestings are already encoded in the document of XML in the form of structural tags so their parsers do not have to use state to figure out the current level of nesting and handle the next piece of text correctly, Such information(structure) is not encoded properly with markdown (quill delta is just markdown in essence).

It's not an easy task to rewrite the whole parser supporting infinite nestings correctly on such a data structure, what I am saying is don't be too ambitious at this stage, say we only support 2 or 3 levels of such nestings, and let users know this explicitly, so you have less cases to implement and worry about.

**Comment by adrian-moisa** [comment]
I see what you mean. Again, great detailed feedback. Much appreciated. I will keep it in mind. It will be a while until I get to check on this one. Most likely I will ask one of my juniors to start tackling this issue. But then again, we have a long list of higher prio issues to handle. So if anyone from the community is willing to step in, I'm happy to coordinate/assist. Cheers!

**Comment by adrian-moisa** [comment]
Closed the ticket since it is a duplicate of #158 which is currently in progress.
