### ISSUE TITLE
Sys - Use `src` convention for folder structure

### ISSUE THREAD

**Issue by friebetill** [visual-space/visual-editor#64]
I suggest that the src convention is used, this has the purpose to separate the library's public code from private implementation code, see [this answer](https://stackoverflow.com/a/58521728/6169345). This also has the advantage that the import is cleaner, because then it's only possible to use `import 'package:visual_editor/visual-editor.dart';` instead of `import 'package:visual_editor/controller/services/editor-controller.dart';`.

Because we can only import public classes without warning the, we have to make the model classes public, e.g. `EmbedM`, `DefaultListBlockStyle`, `BlockEmbedM`, `ChangeSource`, etc. .

**Comment by adrian-moisa** [comment]
Thank you for filling up the ticket. I'll be reviewing the details and fixing it as soon as I'm done with more pressing issues.
