### ISSUE TITLE
Caret - The caret shouldn't be displayed in read-only mode

### ISSUE THREAD

**Issue by sebastian0107** [visual-space/visual-editor#73]
The caret indicates that the text can be edited, so it is useless to display it in the read-only mode

**Comment by adrian-moisa** [comment]
The caret is no longer displayed in readonly mode. The `showCursor` configuration option for `VisualEditor` was removed. It makes no sense to have the cared showing up in readonly mode. Or the caret missing in editable mode.

Closed and pushed. Cheers!
